## Mold Violation Dataset Preprocessing
This notebook is for filtering and preprocessing the Mold Violations DAtaset obtained through: https://data.cityofnewyork.us/Housing-Development/MOLD-VIOLATIONS-RECENT/wguz-g589/data

THe idea is to use this dataset to identify the location, building ID of buildings that have or had mold in their past down to 2010. 
COlumns exported: 'BBL','InspectionDate','Latitude','Longitude','Postcode','CurrentStatus','CurrentStatusDate'

In [161]:
#Import stuff
import pandas as pd
import numpy as np

In [162]:
#import Dataset as Dataframe
Mold_violations=pd.read_csv('..\Data\MOLD_VIOLATIONS-_RECENT.csv')

In [163]:
Mold_violations.head()

,InspectionDate,HouseNumber,StreetName,Apartment,Borough,ViolationID,CurrentStatus,NOVDescription,BuildingID,Class,...,NovType,ViolationStatus,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
0,10/15/2020,225,23 STREET,3R,BROOKLYN,13957715,VIOLATION CLOSED,SECTION 27-2017.3 HMC: TRACE AND REPAIR THE SO...,146093,C,...,Original,Close,40.660628,-73.995235,7.0,38.0,145.0,3009467.0,3.006460e+09,Sunset Park West
1,09/13/2020,169,NEW YORK AVENUE,1FL,BROOKLYN,13815086,VIOLATION CLOSED,SECTION 27-2017.3 HMC: TRACE AND REPAIR THE SO...,343609,C,...,Original,Close,40.674401,-73.947279,8.0,36.0,341.0,3031027.0,3.012280e+09,Crown Heights North
2,06/22/2021,1503,METROPOLITAN AVENUE,MA,BRONX,14402160,VIOLATION DISMISSED,SECTION 27-2017.3 HMC: TRACE AND REPAIR THE SO...,95875,C,...,Original,Close,40.839228,-73.858855,9.0,18.0,21001.0,2096702.0,2.039448e+09,Parkchester
3,08/28/2019,1635,UNION STREET,C1,BROOKLYN,13965940,VIOLATION CLOSED,SECTION 27-2017.3 HMC: TRACE AND REPAIR THE SO...,383387,C,...,Original,Close,40.668096,-73.935991,9.0,35.0,353.0,3037536.0,3.013950e+09,Crown Heights North
4,07/13/2021,667,WEST 161 STREET,1C,MANHATTAN,14437717,VIOLATION CLOSED,SECTION 27-2017.3 HMC: TRACE AND REPAIR THE SO...,42926,C,...,Original,Close,40.837586,-73.945488,12.0,7.0,247.0,1063334.0,1.021360e+09,Washington Heights South

In [164]:
# Mold_violations.isna().any()

In [165]:
#selected potentially important columns. filter dates for everything newer 2010. 
Mold_violations=Mold_violations[['BBL','InspectionDate','Latitude','Longitude','Postcode','CurrentStatus','CurrentStatusDate']].loc[Mold_violations.InspectionDate >= '01/01/2010']
#Switch InspectionDate to pd datetime 
Mold_violations.InspectionDate = pd.to_datetime(Mold_violations.InspectionDate)
Mold_violations=Mold_violations.sort_values(by='InspectionDate')
print('length of df before dropNA: ',Mold_violations.size)
#drop Nan values
Mold_violations=Mold_violations.dropna()
print('length of df after dropNA: ',Mold_violations.size)
#switch bbl,postcode to int
Mold_violations[['BBL','Postcode']]= Mold_violations[['BBL','Postcode']].astype('int')

length of df before dropNA:  195979
length of df after dropNA:  195650

In [171]:
#Check for remaining null values
Mold_violations[pd.isnull(Mold_violations).any(axis=1)]

Empty DataFrame
Columns: [BBL, InspectionDate, Latitude, Longitude, Postcode, CurrentStatus, CurrentStatusDate]
Index: []

In [172]:
#write Csv
Mold_violations.to_csv('../Output/MoldViolationsCleaned.csv')